name: alchemy
favicon: null
layout_spectrum: 0.09978981106542051
typography_spectrum: 0.43064427096396685
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.9945911301765591
  lightness: 0.13759630266577005
  saturation: 0.4319951075594872
  rhythmicContrast: 0.820461573312059
purpose: []
